### ISSUE TITLE
Flatpak Package

### ISSUE THREAD

**Issue by RilicTheFox** [Bali10050/Darkly#91]
Currently, while the theme works on the base system, it does not work in flatpak-installed applications. This is because flatpak uses a different runtime environment to the rest of the system, requiring Darkly to be installed as a flatpak package to be seen by applications running within it.

There is a Lightly fork that "ports" it into a Flatpak package here: https://github.com/MicrogamerCz/Lightly

Kvantum also has a flatpak package that is published on Flathub: https://github.com/flathub/org.kde.KStyle.Kvantum

**Comment by Bali10050** [comment]
[XDG Desktop Portal](https://wiki.archlinux.org/title/XDG_Desktop_Portal) should solve that issue

**Comment by RilicTheFox** [comment]
> [XDG Desktop Portal](https://wiki.archlinux.org/title/XDG_Desktop_Portal) should solve that issue

I have XDG desktop portal installed for KDE and it does not solve the issue. Reading that page, seems that portals don't pass through themes or kstyles, only the UI toolkit to be used by applications like Firefox. In order to use kstyles, they seemingly need to be installed via a flatpak package.

**Comment by DeltaCopy** [comment]
I've used https://github.com/MicrogamerCz/Lightly made several changes, and was able to build a flatpak bundle file for Darkly.

With limited testing Dolphin and Okular does not adopt the theme and continue to use the default Breeze style,  even though I set `flatpak override --env=QT_STYLE_OVERRIDE=Darkly $flatpak_app`. I guess some flatpak applications don't support the style override.

I did however have success with VLC when installed as a flatpak and it shows up as a theme to select from within the application.

@RilicTheFox further testing is required, which flatpak applications specifically are you looking for Darkly theme to be applied to ?

**Comment by DeltaCopy** [comment]
Closing this, as I am not comfortable releasing this in a partial state without thorough testing.
